apiVersion: v1
kind: Namespace
metadata:
  name: agent
---
apiVersion: v1
kind: Namespace
metadata:
  name: payments
---
apiVersion: v1
kind: Namespace
metadata:
  name: checkout
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
